name: genbed

channels:
  - defaults
  - conda-forge

dependencies:
  - python = 3
  - numpy
  - scipy
  - pandas = 1
  - scikit-learn >= 0.22
  - shap >= 0.30
  - statsmodels
  - matplotlib
  - seaborn >= 0.11
  - ipython
  - jupyter
  - pip
  - pip:
    - watermark
